apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebappcontainer
    image: docker2236/java-web-application:1
    ports:
    - containerPort: 8080
  - name: nginxcontainer
    image: nginx
    ports:
    - containerPort: 80
            
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice
spec:
  type: NodePort
  selector: 
    app: javawebapp
  ports:
  - name: javaappport
    port: 8080
    targetPort: 8080
  - name: nginxport
    port: 80
    targetPort: 80
    

