apiVersion: v1
kind: ReplicationController
metadata: 
  name: mavenwebapprc
  namespace: test-ns
spec:
  replicas: 2
  selector:
    app: mavenwebapp
  template: #pod template
    metadata:
        name: mavenwebapppod
        labels:
          app: mavenwebapp
    spec: 
      containers:
      - name: mavenwebappcontainer
        image: docker2236/maven-web-application:1
        ports:
        - containerPort: 8080
