apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeploy
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  minReadySeconds: 30
  # revisionHitoryLimit: 5
  template: #pod template
    metadata:
        name: javawebapppod
        labels:
          app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: docker2236/java-web-application:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - name: javawebappport
    port: 80
    targetPort: 8080

